name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/hotfix\/.+/'
    title:
      - '/fix/i'
      - '/hotfix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    body:
      - '/LP-[0-9]{1,4}/'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## What's changed

  $CHANGES
