name: Deploy

on:
  workflow_run:
    workflows: ["Build & push services image", "E2E Tests on Ephemeral environment"]
    branches: [main, test]
    types:
      - completed
      - requested

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}

      - run: sleep 10s

      - name: Deployed
        run: echo '::set-output name=summary::green'

