name: Deploy

on:
  workflow_run:
    workflows:
      - Build & push services image
      - Test
    types:
      - completed

jobs:
  dependencies:
    name: Dependency workflows
    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - name: Echo sha ref
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}

      - name: Echo conclussion
        run: echo ${{ github.event.workflow_run.conclusion }}

      - name: Echo workflow_run
        run: echo ${{ github.event.workflow_run }}

      - run: sleep 10s

      - name: Deployed
        run: echo '::set-output name=summary::green'

