name: Build & push services image

on: push

jobs:
  service-build-push:
    name: Build and Push (Test me boy)
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       services: [test1, test2]

    steps:
      - run: sleep 3s


  build-and-push-completed:
    name: Build and Push completed
    runs-on: ubuntu-20.04
    needs: [service-build-push]

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-and-push-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Finished building and Publishing
        run: echo "Conclusion step for all services image building and pushing. This is a dependency for E2E ephemeral test"
