name: Build & push services image

on: push

jobs:
  prepate-checks:
    name: Prepare check
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Check Runs
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checks: |
            [
              { "id": "build-completed", "name": "Build completed" }
            ]
          status: "queued"

  service-build-push:
    name: Build and Push
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       services: [test1, test2]

    steps:
      - run: sleep 10s


  build-and-push-completed:
    name: Build and Push completed
    runs-on: ubuntu-20.04
    needs: [service-build-push]

    steps:
      - name: Report build Conclusion
        if: always()
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: build-completed
          conclusion: ${{ steps.service-build-push.outcome }}
