name: Build & push services image

on: push

jobs:
  service-build-push:
    name: Build and Push
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       services: [test1, test2]

    steps:
      - run: sleep 10s


  build-and-push-completed:
    name: Build and Push completed
    runs-on: ubuntu-20.04
    needs: [service-build-push]

    steps:
      - name: Report build Conclusion
        run: echo "build done"
