name: Build & push services image

on: push

jobs:
  service-build-push:
    name: Build and Push
    runs-on: ubuntu-20.04
    strategy:
      matrix:
       services: [test1, test2]

    steps:
      - run: sleep 10s


  build-and-push-completed:
    name: Build and Push completed
    runs-on: ubuntu-20.04
    needs: [service-build-push]

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-and-push-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Report build Conclusion
        run: echo "build done"
