name: E2E Tests on Ephemeral environment

on:
  repository_dispatch:
    types: [build-and-push-passed]

jobs:
  build-ephemeral-environment:
    name: Build environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [test1, test2]

    steps:
      - name: Echo
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}

      - name: test
        run: echo '::set-output name=summary::green'

  build-ephemeral-done:
    name: Ephemeral completion
    runs-on: ubuntu-latest
    needs: build-ephemeral-environment

    steps:
      - name: Echo
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}

