name: E2E Tests on Ephemeral environment

on:
  repository_dispatch:
    types: [build-and-push-passed]

jobs:
  build-ephemeral-environment:
    name: Build environment
    runs-on: ubuntu-latest

    steps:
      - name: Done
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}
