name: E2E Tests on Ephemeral environment

on: push

jobs:
  wait-for-build:
    name: Build environment
    runs-on: ubuntu-latest

    steps:
      - name: Wait on tests
        # or lewagon/wait-on-check-action@master, but master is not guaranteed to be stable ATM
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'build-and-push-completed'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds

  build-ephemeral-environment:
    name: Build environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [test1, test2]

    steps:
      - name: Echo
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}

      - name: test
        run: echo '::set-output name=summary::green'

  build-ephemeral-done:
    name: Ephemeral completion
    runs-on: ubuntu-latest
    needs: build-ephemeral-environment

    steps:
      - name: Echo
        run: echo ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.ref }}

