name: Workflow dispatch create PR

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  environments: ["test", "stg", "prd"]

jobs:
  add_labels:
    name: Add labels automatically
    runs-on: ubuntu-latest

    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: test

      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            ${{ env.environments }}


