name: Workflow dispatch create PR

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  environments: "test\nstg\nprd"

jobs:
  add_labels:
    name: Add labels automatically
    runs-on: ubuntu-latest

    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: test

      - uses: actions/github-script@v4
        id: scriptPR
        with:
          script: |
            const script = require('./.github/scripts/add-labels.js')
            await script({github, core}, ${{ github.repository }}, ${{ github.event.number }}, ["test","input","else"])


