name: Test

on: push

jobs:
  deployment:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Action failed')

      - name: Tested
        run: echo '::set-output name=summary::green'

