name: Test

on: push

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  deployment:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);

      - run: echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        shell: bash

      - run: |
          echo PR #${{ github.event.number }} has been merged
          echo context #${{ github.event }}

      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Action failed')

      - name: Tested
        run: echo '::set-output name=summary::green'

