name: E2E Tests on Ephemeral environment

on:
  workflow_run:
    workflows: [ "Build & push services imagev" ]
    types: [completed]

jobs:
  build-ephemeral-environment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build environment
    runs-on: ubuntu-latest

    steps:
      - name: Done
        run: echo "Sucesss, go home"
