name: Test

on: push

jobs:
  deployment:
    name: Testing
    runs-on: ubuntu-latest

    steps:
     - uses: jwalton/gh-find-current-pr@v1
          id: findPr
          with:
            # Can be "open", "closed", or "all".  Defaults to "open".
            state: all
        # This will echo "Your PR is 7", or be skipped if there is no current PR.
        - run: echo "Your PR is ${PR}"
          if: success() && steps.findPr.outputs.number
          env:
            PR: ${{ steps.findPr.outputs.pr }}

      - run: |
          echo "PR #${{ github.event.number }} has been merged";
          echo "context #${{ github.event }}";

      - run: |
         echo "$GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'"
         echo "github.event.number = ${{ github.event.number  }}"
         echo "github.event.pull_request.number = ${{ github.event.pull_request.number }}"
         echo "github.event.issue.number = ${{ github.event.issue.number }}"

      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Action failed')

      - name: Tested
        run: echo '::set-output name=summary::green'

