name: Test

on: push

jobs:
  deployment:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - run: echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        shell: bash

      - run: |
          echo PR #${{ github.event.number }} has been merged
          echo context #${{ github.event }}

      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Action failed')

      - name: Tested
        run: echo '::set-output name=summary::green'

