name: Workflow dispatch create PR

on:
  workflow_dispatch:
    inputs:
      origin-commit-sha:
        description: "The commit SHA that generated the trigger"
        required: false
        default: 'false'

jobs:
  workflow_dispatch:
    name: Manual PR Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: date >> date.info

      - uses: actions/github-script@v4
        id: getPRDetails
        if: github.event.inputs.origin-commit-sha != 'false'
        env:
          repoOwner: 'enzymejs'
          repoName: 'enzyme-matchers'
          SHA: ${{ github.event.inputs.origin-commit-sha }}
        with:
          script: |
            const script = require('./.github/scripts/get-pr-details.js')
            await script({github, core})

      - uses: actions/github-script@v4
        id: constructPR
        with:
          script: |
            const script = require('./.github/scripts/construct-pr-text.js')
            script('${{ github.event.inputs.origin-commit-sha }}', '${{ steps.getPRDetails.outputs.prNumber }}','${{ steps.getPRDetails.outputs.title }}', btoa('${{ steps.getPRDetails.outputs.body }}'), { core })

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ${{ steps.constructPR.outputs.commit-message }}
          title: ${{ steps.constructPR.outputs.title }}
          body: ${{ steps.constructPR.outputs.body }}
          branch: release/test-oci-image-${{ github.event.inputs.oci-image-tag }}

